[env:esp32dev]
platform = espressif32
upload_port = COM12
framework = arduino
board = m5stack-core2
test_framework = googletest
lib_deps = 
    m5stack/M5Core2
build_unflags = -std=gnu++11
build_flags = 
    -std=gnu++14
    -D M5STACK_M5CORE2 