[platformio]
src_dir = secondary

[env:esp32dev]
platform = espressif32
board = m5stack-core2
framework = arduino
upload_port = /dev/ttyACM0
test_framework = googletest
lib_deps = m5stack/M5Core2

extra_scripts = extra_script.py

build_unflags = -std=gnu++11
build_flags =
  -std=gnu++14
  -D M5STACK_M5CORE2
  -I ${PROJECT_DIR}/../../include
  -I ${PROJECT_DIR}/../../h6x_dynamic_packet_handler/include
